export const CATEGORIES = [
  { key: "all", icon: "⚡", en: "All", ru: "Все", accent: "#ffffff" },
  { key: "sword", icon: "⚔️", en: "Sword", ru: "Меч", accent: "#ef5350" },
  { key: "axe", icon: "🪓", en: "Axe", ru: "Топор", accent: "#a1887f" },
  { key: "bow", icon: "🏹", en: "Bow", ru: "Лук", accent: "#66bb6a" },
  {
    key: "crossbow",
    icon: "🎯",
    en: "Crossbow",
    ru: "Арбалет",
    accent: "#42a5f5",
  },
  {
    key: "trident",
    icon: "🔱",
    en: "Trident",
    ru: "Трезубец",
    accent: "#26c6da",
  },
  { key: "armor", icon: "🛡️", en: "Armor", ru: "Броня", accent: "#5c6bc0" },
  { key: "helmet", icon: "⛑️", en: "Helmet", ru: "Шлем", accent: "#ffa726" },
  {
    key: "chestplate",
    icon: "🦺",
    en: "Chestplate",
    ru: "Нагрудник",
    accent: "#ef6c00",
  },
  {
    key: "leggings",
    icon: "🩲",
    en: "Leggings",
    ru: "Поножи",
    accent: "#ab47bc",
  },
  { key: "boots", icon: "👢", en: "Boots", ru: "Ботинки", accent: "#8d6e63" },
  {
    key: "tool",
    icon: "⛏️",
    en: "Tools",
    ru: "Инструменты",
    accent: "#78909c",
  },
  { key: "hoe", icon: "🌾", en: "Hoe", ru: "Мотыга", accent: "#9ccc65" },
  {
    key: "fishing",
    icon: "🎣",
    en: "Fishing Rod",
    ru: "Рыбалка",
    accent: "#00acc1",
  },
  { key: "elytra", icon: "🪂", en: "Elytra", ru: "Элитра", accent: "#ec407a" },
];
