export const ENCHANTMENTS = [
  // ─── SWORD ────────────────────────────────────────────────
  {
    name: "Abiding",
    nameRu: "Нерушимость",
    desc: "Weapons with this enchant become unbreakable",
    descRu: "Оружие с этим зачарованием становится нерушимым",
    apply: ["sword", "axe"],
    rarity: "Legendary",
    maxLevel: 1,
  },
  {
    name: "Allure",
    nameRu: "Притяжение",
    desc: "Your attack pulls mobs towards you",
    descRu: "Притягивает мобов при атаке",
    apply: ["sword"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Ambit",
    nameRu: "Радиус",
    desc: "Damages mobs within a radius that increases with level",
    descRu: "Наносит урон мобам в радиусе, который растёт с уровнем",
    apply: ["sword", "axe"],
    rarity: "Ultimate",
    maxLevel: 7,
  },
  {
    name: "Beastslayer",
    nameRu: "Истребитель",
    desc: "Increases damage dealt to Hostile Mobs",
    descRu: "Увеличивает урон по враждебным мобам",
    apply: ["sword", "axe"],
    rarity: "Legendary",
    maxLevel: 4,
  },
  {
    name: "Berserk",
    nameRu: "Берсерк",
    desc: "Chance of Strength and Mining Fatigue",
    descRu: "Шанс получить силу и усталость от добычи",
    apply: ["sword", "axe"],
    rarity: "Unique",
    maxLevel: 5,
  },
  {
    name: "Blind",
    nameRu: "Слепота",
    desc: "A chance of causing blindness when attacking",
    descRu: "Шанс ослепить врага при атаке",
    apply: ["sword"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Block",
    nameRu: "Блок",
    desc: "A chance to negate an attack and deal up to 4 damage back",
    descRu: "Шанс отменить удар и нанести до 4 урона в ответ",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Bone Crusher",
    nameRu: "Дробитель костей",
    desc: "Increases damage dealt to Skeletons",
    descRu: "Увеличивает урон по скелетам",
    apply: ["sword", "axe"],
    rarity: "Simple",
    maxLevel: 3,
  },
  {
    name: "Confuse",
    nameRu: "Замешательство",
    desc: "Chance to give nausea effect",
    descRu: "Шанс вызвать тошноту у врага",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 4,
  },
  {
    name: "Critical",
    nameRu: "Критика",
    desc: "Increases damage done with critical hit",
    descRu: "Увеличивает урон от критических ударов",
    apply: ["sword"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Death Punch",
    nameRu: "Удар смерти",
    desc: "Increases damage dealt to Zombies",
    descRu: "Увеличивает урон по зомби",
    apply: ["sword", "axe"],
    rarity: "Simple",
    maxLevel: 5,
  },
  {
    name: "Decapitation",
    nameRu: "Обезглавливание",
    desc: "Chance to have opponent's head drop on death",
    descRu: "Шанс выбить голову врага при смерти",
    apply: ["sword", "axe"],
    rarity: "Simple",
    maxLevel: 3,
  },
  {
    name: "Deranged",
    nameRu: "Безумие",
    desc: "Strike lightning at nearby players",
    descRu: "Бьёт молнией по ближайшим игрокам",
    apply: ["sword"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Devour",
    nameRu: "Пожирание",
    desc: "Chance to restore food while killing mobs",
    descRu: "Шанс восстановить еду при убийстве мобов",
    apply: ["sword", "axe"],
    rarity: "Unique",
    maxLevel: 3,
  },
  {
    name: "Diploid",
    nameRu: "Диплоид",
    desc: "Chance to multiply mob drops. Costs 5 souls / activation",
    descRu: "Шанс умножить дроп с мобов. Стоит 5 душ/активацию",
    apply: ["sword"],
    rarity: "Fabled",
    maxLevel: 5,
  },
  {
    name: "Disappear",
    nameRu: "Исчезновение",
    desc: "Chance to become invisible when low on health",
    descRu: "Шанс стать невидимым при малом HP",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 4,
  },
  {
    name: "Disarm",
    nameRu: "Разоружение",
    desc: "Chance to disarm opponent",
    descRu: "Шанс разоружить противника",
    apply: ["sword"],
    rarity: "Fabled",
    maxLevel: 3,
  },
  {
    name: "Disarmor",
    nameRu: "Снятие брони",
    desc: "Chance of unequipping random armor piece from your opponent",
    descRu: "Шанс снять случайный элемент брони с противника",
    apply: ["sword"],
    rarity: "Legendary",
    maxLevel: 8,
  },
  {
    name: "Disintegrate",
    nameRu: "Разрушение",
    desc: "Chance to deal extra durability damage to all enemy armor",
    descRu: "Шанс нанести доп. урон прочности всей броне врага",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 4,
  },
  {
    name: "Distance",
    nameRu: "Дистанция",
    desc: "Chance to distance yourself from enemies and gain regeneration",
    descRu: "Шанс отдалиться от врага и получить регенерацию",
    apply: ["sword", "axe"],
    rarity: "Ultimate",
    maxLevel: 4,
  },
  {
    name: "Double Strike",
    nameRu: "Двойной удар",
    desc: "A chance to strike twice",
    descRu: "Шанс ударить дважды",
    apply: ["sword"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Ender Slayer",
    nameRu: "Убийца эндера",
    desc: "Increases damage dealt to Enderman and Ender Dragon",
    descRu: "Увеличивает урон по эндерменам и дракону",
    apply: ["sword", "axe"],
    rarity: "Elite",
    maxLevel: 5,
  },
  {
    name: "Endmaster",
    nameRu: "Властелин эндера",
    desc: "Deal double damage to mobs in the End",
    descRu: "Двойной урон по мобам в Эндере",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Epicness",
    nameRu: "Эпичность",
    desc: "Display particles on attack",
    descRu: "Отображает частицы при атаке",
    apply: ["sword"],
    rarity: "Simple",
    maxLevel: 3,
  },
  {
    name: "Exalted",
    nameRu: "Возвышение",
    desc: "A chance of removing bad potion effects",
    descRu: "Шанс снять негативные зелья-эффекты с себя",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 4,
  },
  {
    name: "Famine",
    nameRu: "Голод",
    desc: "A chance to give your opponent the hunger effect",
    descRu: "Шанс вызвать голод у противника",
    apply: ["sword", "axe"],
    rarity: "Unique",
    maxLevel: 4,
  },
  {
    name: "Featherweight",
    nameRu: "Лёгкость",
    desc: "Chance to get a burst of Haste",
    descRu: "Шанс получить ускорение",
    apply: ["sword", "axe"],
    rarity: "Unique",
    maxLevel: 3,
  },
  {
    name: "Forcefield",
    nameRu: "Силовое поле",
    desc: "Chance to push away your opponent",
    descRu: "Шанс оттолкнуть противника",
    apply: ["sword"],
    rarity: "Simple",
    maxLevel: 5,
  },
  {
    name: "Fuddle",
    nameRu: "Мешанина",
    desc: "Disorganize opponent's hotbar",
    descRu: "Перепутывает слоты горячей панели врага",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Greatsword",
    nameRu: "Двуручник",
    desc: "Multiplies damage against players wielding a Bow",
    descRu: "Умножает урон по игрокам с луком в руках",
    apply: ["sword"],
    rarity: "Elite",
    maxLevel: 5,
  },
  {
    name: "Ice Aspect",
    nameRu: "Ледяное лезвие",
    desc: "A chance of causing slowness when attacking",
    descRu: "Шанс замедлить врага при атаке",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Immolation",
    nameRu: "Воспламенение",
    desc: "Set all mobs in radius on fire",
    descRu: "Поджигает всех мобов в радиусе",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Infernal",
    nameRu: "Инфернал",
    desc: "Explosive fire effect",
    descRu: "Взрывной огненный эффект",
    apply: ["sword", "axe"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Inquisitive",
    nameRu: "Любопытство",
    desc: "Chance to increase EXP drops from mobs",
    descRu: "Шанс получить больше опыта с мобов",
    apply: ["sword"],
    rarity: "Legendary",
    maxLevel: 4,
  },
  {
    name: "Interrupt",
    nameRu: "Прерывание",
    desc: "Chance to give your enemy Mining Fatigue",
    descRu: "Шанс дать врагу усталость от добычи",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 2,
  },
  {
    name: "Kill Aura",
    nameRu: "Аура убийства",
    desc: "Chance to kill multiple monsters in radius",
    descRu: "Шанс убить нескольких мобов в радиусе",
    apply: ["sword"],
    rarity: "Legendary",
    maxLevel: 5,
  },
  {
    name: "Launch",
    nameRu: "Запуск",
    desc: "Launch yourself by right-clicking",
    descRu: "Подбрасывает тебя при ПКМ",
    apply: ["sword"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Lifesteal",
    nameRu: "Похищение жизни",
    desc: "A chance to steal health when attacking",
    descRu: "Шанс украсть здоровье при атаке",
    apply: ["sword"],
    rarity: "Legendary",
    maxLevel: 5,
  },
  {
    name: "Magnet",
    nameRu: "Магнит",
    desc: "Your attack pulls players towards you",
    descRu: "Атака притягивает игроков к тебе",
    apply: ["sword"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Nether Slayer",
    nameRu: "Убийца Незера",
    desc: "Increases damage dealt to nether mobs",
    descRu: "Увеличивает урон по мобам Незера",
    apply: ["sword", "axe"],
    rarity: "Elite",
    maxLevel: 5,
  },
  {
    name: "Netherling",
    nameRu: "Нижний мир",
    desc: "Double damage to mobs in Nether",
    descRu: "Двойной урон по мобам в Незере",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Night Owl",
    nameRu: "Ночная сова",
    desc: "Deal more damage to mobs at night",
    descRu: "Больше урона по мобам ночью",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 1,
  },
  {
    name: "Nightwalker",
    nameRu: "Ночной ходок",
    desc: "Freeze mobs at night",
    descRu: "Замораживает мобов ночью",
    apply: ["sword"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Paralyze",
    nameRu: "Паралич",
    desc: "Gives lightning effect and a chance for slowness and slow swinging",
    descRu: "Молния и шанс замедления + усталости атаки",
    apply: ["sword", "axe"],
    rarity: "Elite",
    maxLevel: 4,
  },
  {
    name: "Permafrost",
    nameRu: "Вечная мерзлота",
    desc: "Chance to slow and bleed opponents",
    descRu: "Шанс замедлить и заставить кровоточить противника",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 5,
  },
  {
    name: "Poison",
    nameRu: "Яд",
    desc: "A chance of giving poison effect",
    descRu: "Шанс отравить врага",
    apply: ["sword", "axe"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Ravenous",
    nameRu: "Ненасытность",
    desc: "Chance to regain hunger while fighting",
    descRu: "Шанс восстановить голод в бою",
    apply: ["sword", "axe"],
    rarity: "Unique",
    maxLevel: 4,
  },
  {
    name: "Rebound",
    nameRu: "Отдача",
    desc: "Gain some health back after kills",
    descRu: "Восстанавливает здоровье после убийств",
    apply: ["sword", "axe"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Scare",
    nameRu: "Испуг",
    desc: "Chance to replace opponent's helmet with a pumpkin",
    descRu: "Шанс заменить шлем противника на тыкву",
    apply: ["sword", "axe"],
    rarity: "Fabled",
    maxLevel: 5,
  },
  {
    name: "Slayer",
    nameRu: "Убийца",
    desc: "Increases damage dealt to Passive Mobs",
    descRu: "Увеличивает урон по пассивным мобам",
    apply: ["sword", "axe"],
    rarity: "Unique",
    maxLevel: 4,
  },
  {
    name: "Soulbound",
    nameRu: "Привязь души",
    desc: "A chance to keep item on death",
    descRu: "Шанс сохранить предмет после смерти",
    apply: ["sword", "axe"],
    rarity: "Fabled",
    maxLevel: 3,
  },
  {
    name: "Soulgrind",
    nameRu: "Жатва душ",
    desc: "Chance to get souls by killing mobs",
    descRu: "Шанс получить души при убийстве мобов",
    apply: ["sword"],
    rarity: "Fabled",
    maxLevel: 3,
  },
  {
    name: "Spiritmaster",
    nameRu: "Мастер духов",
    desc: "Chance to get more souls from killing players",
    descRu: "Шанс получить больше душ при убийстве игроков",
    apply: ["sword"],
    rarity: "Fabled",
    maxLevel: 3,
  },
  {
    name: "Strike",
    nameRu: "Удар молнии",
    desc: "Chance to strike lightning at the opponent",
    descRu: "Шанс ударить молнией по противнику",
    apply: ["sword", "bow", "crossbow", "trident"],
    rarity: "Simple",
    maxLevel: 3,
  },
  {
    name: "Striker",
    nameRu: "Стрелок",
    desc: "Rain arrows over opponent",
    descRu: "Дождь стрел над противником",
    apply: ["sword"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Suspend",
    nameRu: "Подвешивание",
    desc: "Chance to cause no knockback to mobs",
    descRu: "Шанс не давать откидывание мобам",
    apply: ["sword"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Thunderlord",
    nameRu: "Громовластитель",
    desc: "Strike monsters with lightning every 3 consecutive hits",
    descRu: "Бьёт мобов молнией каждые 3 удара подряд",
    apply: ["sword", "axe"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Vampire",
    nameRu: "Вампир",
    desc: "A chance to heal you for up to 3hp after you strike",
    descRu: "Шанс исцелиться до 3HP после удара",
    apply: ["sword"],
    rarity: "Elite",
    maxLevel: 3,
  },

  // ─── AXE ──────────────────────────────────────────────────
  {
    name: "Arrow Break",
    nameRu: "Отбив стрелы",
    desc: "Chance for arrows to bounce off you while holding this item",
    descRu: "Шанс отбить стрелы при удержании предмета",
    apply: ["axe"],
    rarity: "Ultimate",
    maxLevel: 6,
  },
  {
    name: "Axe of Spirits",
    nameRu: "Топор духов",
    desc: "Chance to get more souls from killing players",
    descRu: "Шанс получить больше душ при убийстве игроков",
    apply: ["axe"],
    rarity: "Fabled",
    maxLevel: 3,
  },
  {
    name: "Barbarian",
    nameRu: "Варвар",
    desc: "Chance to inflict more axe damage",
    descRu: "Шанс нанести дополнительный урон топором",
    apply: ["axe"],
    rarity: "Legendary",
    maxLevel: 4,
  },
  {
    name: "Blacksmith",
    nameRu: "Кузнец",
    desc: "Repair your weapon in exchange for dealing less damage",
    descRu: "Ремонтирует оружие в обмен на меньший урон",
    apply: ["axe"],
    rarity: "Legendary",
    maxLevel: 5,
  },
  {
    name: "Bleed",
    nameRu: "Кровотечение",
    desc: "Make your opponent bleed",
    descRu: "Заставляет противника истекать кровью",
    apply: ["axe"],
    rarity: "Ultimate",
    maxLevel: 6,
  },
  {
    name: "Blunt Force",
    nameRu: "Тупая сила",
    desc: "Chance to strike with great force",
    descRu: "Шанс ударить с огромной силой",
    apply: ["axe"],
    rarity: "Elite",
    maxLevel: 4,
  },
  {
    name: "Cleave",
    nameRu: "Рубка",
    desc: "Damages players within a radius that increases with level",
    descRu: "Наносит урон игрокам в радиусе (растёт с уровнем)",
    apply: ["axe"],
    rarity: "Ultimate",
    maxLevel: 7,
  },
  {
    name: "Diminish",
    nameRu: "Ослабление",
    desc: "Chance to give your enemy Mining Fatigue",
    descRu: "Шанс дать врагу усталость от добычи",
    apply: ["axe"],
    rarity: "Ultimate",
    maxLevel: 1,
  },
  {
    name: "Immolate",
    nameRu: "Воспламенение",
    desc: "Increases damage dealt to Spiders",
    descRu: "Увеличивает урон по паукам",
    apply: ["axe"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Inflame",
    nameRu: "Поджог",
    desc: "Set all players in radius on fire",
    descRu: "Поджигает всех игроков в радиусе",
    apply: ["axe"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Reaper",
    nameRu: "Жнец",
    desc: "Chance to inflict Wither and Blindness when dealing damage",
    descRu: "Шанс наложить иссушение и слепоту с уроном",
    apply: ["axe"],
    rarity: "Elite",
    maxLevel: 4,
  },
  {
    name: "Shatter",
    nameRu: "Разрушитель",
    desc: "Chance to deal extra durability damage to all enemy armor",
    descRu: "Шанс нанести доп. урон прочности всей броне врага",
    apply: ["axe"],
    rarity: "Ultimate",
    maxLevel: 4,
  },
  {
    name: "Timber",
    nameRu: "Лесоруб",
    desc: "Chance to break a tree in one hit",
    descRu: "Шанс срубить дерево одним ударом",
    apply: ["axe"],
    rarity: "Ultimate",
    maxLevel: 3,
  },

  // ─── BOW ──────────────────────────────────────────────────
  {
    name: "Archer",
    nameRu: "Лучник",
    desc: "Increases damage dealt with bows",
    descRu: "Увеличивает урон из луков",
    apply: ["bow"],
    rarity: "Ultimate",
    maxLevel: 4,
  },
  {
    name: "Bowmaster",
    nameRu: "Мастер лука",
    desc: "Multiplies damage against players wielding a Sword",
    descRu: "Умножает урон по игрокам с мечом в руках",
    apply: ["bow", "crossbow", "trident"],
    rarity: "Elite",
    maxLevel: 5,
  },
  {
    name: "Explosive",
    nameRu: "Взрывные стрелы",
    desc: "Chance for arrows to explode",
    descRu: "Шанс взрывных стрел",
    apply: ["bow"],
    rarity: "Unique",
    maxLevel: 5,
  },
  {
    name: "Hellfire",
    nameRu: "Адский огонь",
    desc: "Arrows turn into fireballs",
    descRu: "Стрелы превращаются в огненные шары",
    apply: ["bow"],
    rarity: "Ultimate",
    maxLevel: 5,
  },
  {
    name: "Hunter",
    nameRu: "Охотник",
    desc: "Increases damage dealt to Passive Mobs",
    descRu: "Увеличивает урон по пассивным мобам",
    apply: ["bow", "crossbow", "trident"],
    rarity: "Unique",
    maxLevel: 4,
  },
  {
    name: "Longbow",
    nameRu: "Длинный лук",
    desc: "Greatly increases damage against players with a bow",
    descRu: "Значительно увеличивает урон по игрокам с луком",
    apply: ["bow"],
    rarity: "Ultimate",
    maxLevel: 4,
  },
  {
    name: "Perish",
    nameRu: "Иссушение",
    desc: "A chance to give the Wither effect",
    descRu: "Шанс наложить иссушение",
    apply: ["bow", "crossbow", "trident"],
    rarity: "Unique",
    maxLevel: 5,
  },
  {
    name: "Piercing",
    nameRu: "Пробой",
    desc: "Inflicts more damage",
    descRu: "Наносит дополнительный урон",
    apply: ["bow"],
    rarity: "Ultimate",
    maxLevel: 5,
  },
  {
    name: "Snare",
    nameRu: "Силок",
    desc: "Chance to slow and fatigue enemies with projectiles",
    descRu: "Шанс замедлить и ослабить врагов снарядами",
    apply: ["bow"],
    rarity: "Elite",
    maxLevel: 4,
  },
  {
    name: "Sniper",
    nameRu: "Снайпер",
    desc: "Headshots with bows deal double damage",
    descRu: "Хедшоты из лука наносят двойной урон",
    apply: ["bow"],
    rarity: "Ultimate",
    maxLevel: 5,
  },
  {
    name: "Soulless",
    nameRu: "Душегуб",
    desc: "Increases damage dealt to Hostile Mobs",
    descRu: "Увеличивает урон по враждебным мобам",
    apply: ["bow", "crossbow", "trident"],
    rarity: "Unique",
    maxLevel: 4,
  },
  {
    name: "Virus",
    nameRu: "Вирус",
    desc: "A chance of giving poison effect",
    descRu: "Шанс отравить врага",
    apply: ["bow", "crossbow", "trident"],
    rarity: "Unique",
    maxLevel: 3,
  },

  // ─── CROSSBOW ─────────────────────────────────────────────
  {
    name: "Frenzy",
    nameRu: "Исступление",
    desc: "Chance for arrows to explode",
    descRu: "Шанс взрывных стрел",
    apply: ["crossbow"],
    rarity: "Unique",
    maxLevel: 5,
  },
  {
    name: "Marksman",
    nameRu: "Меткач",
    desc: "Increases damage dealt with Crossbows",
    descRu: "Увеличивает урон из арбалетов",
    apply: ["crossbow"],
    rarity: "Elite",
    maxLevel: 4,
  },
  {
    name: "Missile",
    nameRu: "Ракета",
    desc: "Arrows turn into fireballs",
    descRu: "Стрелы превращаются в огненные шары",
    apply: ["crossbow"],
    rarity: "Elite",
    maxLevel: 5,
  },
  {
    name: "Neutralize",
    nameRu: "Нейтрализация",
    desc: "Chance to disarm opponent",
    descRu: "Шанс разоружить противника",
    apply: ["bow", "crossbow"],
    rarity: "Fabled",
    maxLevel: 2,
  },

  // ─── TRIDENT ──────────────────────────────────────────────
  {
    name: "Chaos",
    nameRu: "Хаос",
    desc: "Deal Weakness and Wither effects",
    descRu: "Накладывает слабость и иссушение",
    apply: ["trident"],
    rarity: "Legendary",
    maxLevel: 5,
  },
  {
    name: "Deadshot",
    nameRu: "Мёртвый выстрел",
    desc: "Headshots with tridents deal double damage",
    descRu: "Хедшоты трезубцем наносят двойной урон",
    apply: ["trident"],
    rarity: "Legendary",
    maxLevel: 5,
  },
  {
    name: "Impact",
    nameRu: "Импакт",
    desc: "Chance to double dealt damage",
    descRu: "Шанс удвоить нанесённый урон",
    apply: ["trident"],
    rarity: "Elite",
    maxLevel: 4,
  },
  {
    name: "Poseidon",
    nameRu: "Посейдон",
    desc: "Increases damage dealt with Tridents",
    descRu: "Увеличивает урон трезубцем",
    apply: ["trident"],
    rarity: "Elite",
    maxLevel: 4,
  },
  {
    name: "Spark",
    nameRu: "Искра",
    desc: "Light opponents on fire",
    descRu: "Поджигает противников",
    apply: ["trident"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Strife",
    nameRu: "Распря",
    desc: "Increases Trident melee damage",
    descRu: "Увеличивает урон трезубцем ближнего боя",
    apply: ["trident"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Twinge",
    nameRu: "Укол",
    desc: "Make your enemy bleed if hit using melee",
    descRu: "Заставляет кровоточить при ударе в ближнем бою",
    apply: ["trident"],
    rarity: "Legendary",
    maxLevel: 4,
  },

  // ─── ARMOR ────────────────────────────────────────────────
  {
    name: "Angelic",
    nameRu: "Ангельское",
    desc: "Heals health when damaged",
    descRu: "Лечит здоровье при получении урона",
    apply: ["armor"],
    rarity: "Ultimate",
    maxLevel: 5,
  },
  {
    name: "Armored",
    nameRu: "Бронированный",
    desc: "Decreases damage from enemy swords by 2% per level",
    descRu: "Снижает урон от мечей противника на 2% за уровень",
    apply: ["armor"],
    rarity: "Legendary",
    maxLevel: 4,
  },
  {
    name: "Arrow Deflect",
    nameRu: "Отклонение стрел",
    desc: "Chance to prevent enemy arrow from dealing damage",
    descRu: "Шанс предотвратить урон от вражеских стрел",
    apply: ["armor"],
    rarity: "Ultimate",
    maxLevel: 4,
  },
  {
    name: "Creeper Armor",
    nameRu: "Броня крипера",
    desc: "Chance to be immune to explosive damage, higher levels can heal",
    descRu: "Шанс иммунитета к взрывам; на высоких уровнях — лечение",
    apply: ["armor"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Curse",
    nameRu: "Проклятие",
    desc: "Chance to give your enemy Mining Fatigue",
    descRu: "Шанс наложить усталость добычи на врага",
    apply: ["armor"],
    rarity: "Elite",
    maxLevel: 2,
  },
  {
    name: "Divert",
    nameRu: "Перенаправление",
    desc: "Chance of poisoning opponent and gaining regeneration",
    descRu: "Шанс отравить атакующего и получить регенерацию",
    apply: ["armor"],
    rarity: "Legendary",
    maxLevel: 5,
  },
  {
    name: "Dodge",
    nameRu: "Уклонение",
    desc: "Chance to dodge physical enemy, higher chance when sneaking",
    descRu: "Шанс уклониться от физической атаки (выше при приседании)",
    apply: ["armor"],
    rarity: "Ultimate",
    maxLevel: 5,
  },
  {
    name: "Frozen",
    nameRu: "Заморозка",
    desc: "Can cause slowness to attacker when defending",
    descRu: "Шанс замедлить атакующего при защите",
    apply: ["armor"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Guardians",
    nameRu: "Стражи",
    desc: "A chance to spawn Iron Golems to assist you",
    descRu: "Шанс призвать железных голема для защиты",
    apply: ["armor"],
    rarity: "Ultimate",
    maxLevel: 10,
  },
  {
    name: "Hardened",
    nameRu: "Закалённый",
    desc: "Chance to recover durability when damaged by players",
    descRu: "Шанс восстановить прочность при получении урона",
    apply: ["armor"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Heavy",
    nameRu: "Тяжёлый",
    desc: "Decreases damage from enemy bows by 2% per level",
    descRu: "Снижает урон от луков врага на 2% за уровень",
    apply: ["armor"],
    rarity: "Ultimate",
    maxLevel: 5,
  },
  {
    name: "Immortal",
    nameRu: "Бессмертие",
    desc: "Chance to prevent your armor from taking durability damage",
    descRu: "Шанс не дать броне терять прочность",
    apply: ["armor"],
    rarity: "Fabled",
    maxLevel: 4,
  },
  {
    name: "Lucid",
    nameRu: "Ясность",
    desc: "Chance to cure blindness and gain night vision when hit",
    descRu: "Шанс вылечить слепоту и получить ночное зрение",
    apply: ["armor"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Molten",
    nameRu: "Расплавленный",
    desc: "Chance of setting your attacker ablaze",
    descRu: "Шанс поджечь атакующего",
    apply: ["armor"],
    rarity: "Unique",
    maxLevel: 4,
  },
  {
    name: "Obsidianshield",
    nameRu: "Щит обсидиана",
    desc: "Gives permanent fire resistance",
    descRu: "Постоянная огнестойкость",
    apply: ["armor"],
    rarity: "Ultimate",
    maxLevel: 1,
  },
  {
    name: "Overload",
    nameRu: "Перегрузка",
    desc: "Unlocks additional hearts",
    descRu: "Разблокирует дополнительные сердца",
    apply: ["armor"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Patch",
    nameRu: "Заплатка",
    desc: "Chance to recover durability when damaged by mobs",
    descRu: "Шанс восстановить прочность при получении урона от мобов",
    apply: ["armor"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Poisoned",
    nameRu: "Ядовитый",
    desc: "Chance to give poison to your attacker",
    descRu: "Шанс отравить атакующего",
    apply: ["armor"],
    rarity: "Elite",
    maxLevel: 4,
  },
  {
    name: "Ragdoll",
    nameRu: "Тряпичная кукла",
    desc: "Chance to be pushed back when getting hit",
    descRu: "Шанс отбросить тебя назад при ударе",
    apply: ["armor"],
    rarity: "Ultimate",
    maxLevel: 4,
  },
  {
    name: "Reflect",
    nameRu: "Отражение",
    desc: "Absorb enemy damage and reflect it back",
    descRu: "Поглощает урон врага и отражает его обратно",
    apply: ["armor"],
    rarity: "Unique",
    maxLevel: 5,
  },
  {
    name: "Reforged",
    nameRu: "Перекованный",
    desc: "Protects weapons and tools durability — items break slower",
    descRu: "Защищает прочность, предметы медленнее ломаются",
    apply: ["armor"],
    rarity: "Elite",
    maxLevel: 10,
  },
  {
    name: "Safeguard",
    nameRu: "Защита",
    desc: "Chance to gain Damage Resistance when defending",
    descRu: "Шанс получить устойчивость к урону при защите",
    apply: ["armor"],
    rarity: "Ultimate",
    maxLevel: 2,
  },
  {
    name: "Spirits",
    nameRu: "Духи",
    desc: "Chance to spawn guard Blazes",
    descRu: "Шанс призвать огненных стражей",
    apply: ["armor"],
    rarity: "Ultimate",
    maxLevel: 10,
  },
  {
    name: "Swordsman",
    nameRu: "Мечник",
    desc: "Chance to reduce incoming damage while wielding a sword (up to 22%)",
    descRu: "Шанс снизить входящий урон при держании меча (до 22%)",
    apply: ["armor"],
    rarity: "Ultimate",
    maxLevel: 5,
  },
  {
    name: "Tank",
    nameRu: "Танк",
    desc: "Chance to decrease damage from enemy axes by 2% per level",
    descRu: "Шанс снизить урон от топоров врага на 2% за уровень",
    apply: ["armor"],
    rarity: "Ultimate",
    maxLevel: 4,
  },
  {
    name: "Trickster",
    nameRu: "Обманщик",
    desc: "When hit, chance to teleport directly behind your opponent",
    descRu: "Шанс телепортироваться за спину атакующего",
    apply: ["armor"],
    rarity: "Elite",
    maxLevel: 8,
  },
  {
    name: "Turmoil",
    nameRu: "Смута",
    desc: "Chance to prevent opponents' guards from spawning",
    descRu: "Шанс помешать вражеским стражам появиться",
    apply: ["armor"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Unholy",
    nameRu: "Нечестивый",
    desc: "Defend with Weakness and Wither effects",
    descRu: "Защищает слабостью и иссушением",
    apply: ["armor"],
    rarity: "Legendary",
    maxLevel: 5,
  },
  {
    name: "Voodoo",
    nameRu: "Вуду",
    desc: "Gives a chance to deal Weakness",
    descRu: "Шанс наложить слабость",
    apply: ["armor"],
    rarity: "Elite",
    maxLevel: 6,
  },
  {
    name: "Ward",
    nameRu: "Страж",
    desc: "A chance to absorb enemy damage",
    descRu: "Шанс поглотить урон врага",
    apply: ["armor"],
    rarity: "Unique",
    maxLevel: 4,
  },
  {
    name: "Wither",
    nameRu: "Иссушение",
    desc: "A chance to give the Wither effect",
    descRu: "Шанс наложить иссушение",
    apply: ["armor"],
    rarity: "Elite",
    maxLevel: 5,
  },

  // ─── HELMET ───────────────────────────────────────────────
  {
    name: "Aquatic",
    nameRu: "Водяной",
    desc: "Breathe underwater",
    descRu: "Дышишь под водой",
    apply: ["helmet"],
    rarity: "Simple",
    maxLevel: 1,
  },
  {
    name: "Glowing",
    nameRu: "Свечение",
    desc: "Gives permanent night vision",
    descRu: "Постоянное ночное зрение",
    apply: ["helmet"],
    rarity: "Simple",
    maxLevel: 1,
  },
  {
    name: "Implants",
    nameRu: "Имплант",
    desc: "Chance to restore food every few seconds",
    descRu: "Шанс восстанавливать еду каждые несколько секунд",
    apply: ["helmet"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Smoke Bomb",
    nameRu: "Дымовая бомба",
    desc: "When near death, spawn a smoke bomb to distract enemies",
    descRu: "При критическом HP создаёт дымовую бомбу для отвлечения врагов",
    apply: ["helmet"],
    rarity: "Elite",
    maxLevel: 8,
  },

  // ─── CHESTPLATE ───────────────────────────────────────────
  {
    name: "Chunky",
    nameRu: "Толстяк",
    desc: "Chance to receive less damage",
    descRu: "Шанс получить меньше урона",
    apply: ["chestplate"],
    rarity: "Legendary",
    maxLevel: 6,
  },
  {
    name: "Fumble",
    nameRu: "Оплошность",
    desc: "Chance to explode enemy when hit by their arrows",
    descRu: "Шанс взорвать врага, когда его стрела тебя попала",
    apply: ["chestplate"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Phoenix",
    nameRu: "Феникс",
    desc: "Chance to revive yourself when killed",
    descRu: "Шанс воскреснуть после смерти",
    apply: ["chestplate"],
    rarity: "Fabled",
    maxLevel: 3,
  },
  {
    name: "Shockwave",
    nameRu: "Ударная волна",
    desc: "Chance to push back your attacker when your health is low",
    descRu: "Шанс отбросить атакующего при малом HP",
    apply: ["chestplate"],
    rarity: "Elite",
    maxLevel: 5,
  },

  // ─── LEGGINGS ─────────────────────────────────────────────
  {
    name: "Explosive Demise",
    nameRu: "Взрывная гибель",
    desc: "Summon Creepers as guards when near death",
    descRu: "Призывает криперов-стражей при критическом HP",
    apply: ["leggings"],
    rarity: "Unique",
    maxLevel: 8,
  },
  {
    name: "Extinguish",
    nameRu: "Тушение",
    desc: "Chance to extinguish yourself when on fire",
    descRu: "Шанс потушить себя при горении",
    apply: ["leggings"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Nulify",
    nameRu: "Аннулирование",
    desc: "Chance to reflect attack and multiply damage. Costs 40 souls",
    descRu: "Шанс отразить атаку и умножить урон. Стоит 40 душ",
    apply: ["leggings"],
    rarity: "Fabled",
    maxLevel: 3,
  },

  // ─── BOOTS ────────────────────────────────────────────────
  {
    name: "Aegis",
    nameRu: "Эгида",
    desc: "Chance to gain speed when taking fall damage",
    descRu: "Шанс получить скорость при падении",
    apply: ["boots"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Aqua",
    nameRu: "Аква",
    desc: "Deal double damage while in water",
    descRu: "Двойной урон под водой",
    apply: ["boots"],
    rarity: "Legendary",
    maxLevel: 4,
  },
  {
    name: "Convulse",
    nameRu: "Конвульсия",
    desc: "Chance to throw your attackers into the air",
    descRu: "Шанс подбросить атакующего в воздух",
    apply: ["boots"],
    rarity: "Legendary",
    maxLevel: 6,
  },
  {
    name: "Gears",
    nameRu: "Шестерни",
    desc: "Added speed when equipped",
    descRu: "Постоянная прибавка к скорости",
    apply: ["boots"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Jelly Legs",
    nameRu: "Мягкое приземление",
    desc: "Chance to negate fall damage",
    descRu: "Шанс отменить урон от падения",
    apply: ["boots"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Lava Walker",
    nameRu: "Ходок по лаве",
    desc: "Walk on Lava",
    descRu: "Ходьба по лаве",
    apply: ["boots"],
    rarity: "Legendary",
    maxLevel: 1,
  },
  {
    name: "Plummet",
    nameRu: "Падение",
    desc: "Deal damage to nearby mobs when taking fall damage",
    descRu: "Наносит урон мобам рядом при падении",
    apply: ["boots"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Rocket Escape",
    nameRu: "Ракетный побег",
    desc: "Blast off into the air at low HP",
    descRu: "Взлетает при критическом HP",
    apply: ["boots"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Springs",
    nameRu: "Пружины",
    desc: "Gives jump boost",
    descRu: "Даёт усиление прыжка",
    apply: ["boots"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Undead Ruse",
    nameRu: "Уловка нежити",
    desc: "Chance to spawn zombie hordes when taking damage",
    descRu: "Шанс призвать орды зомби при получении урона",
    apply: ["boots"],
    rarity: "Elite",
    maxLevel: 10,
  },
  {
    name: "Water Walker",
    nameRu: "Ходок по воде",
    desc: "Walk on Water",
    descRu: "Ходьба по воде",
    apply: ["boots"],
    rarity: "Legendary",
    maxLevel: 1,
  },
  {
    name: "Wings",
    nameRu: "Крылья",
    desc: "Allows flying when worn",
    descRu: "Позволяет летать при ношении",
    apply: ["boots"],
    rarity: "Legendary",
    maxLevel: 1,
  },

  // ─── TOOLS ────────────────────────────────────────────────
  {
    name: "Experience",
    nameRu: "Опыт",
    desc: "Chance to get more experience from ores",
    descRu: "Шанс получить больше опыта с руд",
    apply: ["tool"],
    rarity: "Simple",
    maxLevel: 5,
  },
  {
    name: "Haste",
    nameRu: "Спешка",
    desc: "Allows you to swing your tools faster",
    descRu: "Позволяет быстрее бить инструментами",
    apply: ["tool"],
    rarity: "Fabled",
    maxLevel: 3,
  },
  {
    name: "Hasten",
    nameRu: "Ускорение",
    desc: "Chance to gain Haste after breaking blocks",
    descRu: "Шанс получить ускорение добычи после разбития блоков",
    apply: ["tool"],
    rarity: "Simple",
    maxLevel: 3,
  },
  {
    name: "Multiplication",
    nameRu: "Умножение",
    desc: "Chance to multiply ore drops. Costs 5 souls / activation",
    descRu: "Шанс умножить выпадение руд. Стоит 5 душ/активацию",
    apply: ["tool"],
    rarity: "Fabled",
    maxLevel: 5,
  },
  {
    name: "Rebreather",
    nameRu: "Ребризер",
    desc: "Chance to regain air when mining underwater",
    descRu: "Шанс восстановить воздух при добыче под водой",
    apply: ["tool"],
    rarity: "Simple",
    maxLevel: 2,
  },
  {
    name: "Replenish",
    nameRu: "Пополнение",
    desc: "Chance to restore food while mining",
    descRu: "Шанс восстановить еду при добыче",
    apply: ["tool"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Restore",
    nameRu: "Восстановление",
    desc: "Upon breaking, chance to lose this enchant and repair 50% durability",
    descRu:
      "При поломке — шанс потерять зачарование, восстановив 50% прочности",
    apply: ["tool"],
    rarity: "Fabled",
    maxLevel: 4,
  },
  {
    name: "Smelting",
    nameRu: "Плавка",
    desc: "Chance to smelt mined blocks",
    descRu: "Шанс автоматически выплавить добытые блоки",
    apply: ["tool"],
    rarity: "Simple",
    maxLevel: 3,
  },
  {
    name: "Soulminer",
    nameRu: "Добытчик душ",
    desc: "Chance to get souls by mining",
    descRu: "Шанс получить души при добыче",
    apply: ["tool"],
    rarity: "Fabled",
    maxLevel: 3,
  },
  {
    name: "Telepathy",
    nameRu: "Телепатия",
    desc: "Automatically places mined blocks into your inventory",
    descRu: "Автоматически кладёт сломанные блоки в инвентарь",
    apply: ["tool"],
    rarity: "Unique",
    maxLevel: 4,
  },
  {
    name: "Trench",
    nameRu: "Траншея",
    desc: "Chance to break in 3x3 area",
    descRu: "Шанс пробить область 3×3",
    apply: ["tool"],
    rarity: "Ultimate",
    maxLevel: 9,
  },
  {
    name: "Unbreakable",
    nameRu: "Нерушимый",
    desc: "Tools with this enchant become unbreakable",
    descRu: "Инструменты с этим зачарованием становятся нерушимыми",
    apply: ["tool"],
    rarity: "Fabled",
    maxLevel: 1,
  },
  {
    name: "Vein Miner",
    nameRu: "Жила",
    desc: "Mine entire vein of ores",
    descRu: "Добывает всю жилу руды целиком",
    apply: ["tool"],
    rarity: "Elite",
    maxLevel: 3,
  },

  // ─── HOE ──────────────────────────────────────────────────
  {
    name: "Carrot Planter",
    nameRu: "Морковный фермер",
    desc: "Plant carrots in a 3x3 area by Shift+right-clicking",
    descRu: "Сажает морковь на 3×3 при Shift+ПКМ",
    apply: ["hoe"],
    rarity: "Simple",
    maxLevel: 3,
  },
  {
    name: "Planter",
    nameRu: "Сеятель",
    desc: "Plant seeds in a 3x3 area by Shift+right-clicking",
    descRu: "Сажает семена на 3×3 при Shift+ПКМ",
    apply: ["hoe"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Potato Planter",
    nameRu: "Картофельный фермер",
    desc: "Plant potatoes in a 3x3 area by Shift+right-clicking",
    descRu: "Сажает картофель на 3×3 при Shift+ПКМ",
    apply: ["hoe"],
    rarity: "Simple",
    maxLevel: 3,
  },
  {
    name: "Replanter",
    nameRu: "Пересев",
    desc: "Replants crops when harvested",
    descRu: "Автоматически пересаживает урожай после сбора",
    apply: ["hoe"],
    rarity: "Unique",
    maxLevel: 1,
  },

  // ─── FISHING ──────────────────────────────────────────────
  {
    name: "Auto Reel",
    nameRu: "Авто-катушка",
    desc: "Automatically reels in the fishing rod when it gets a bite",
    descRu: "Автоматически сматывает удочку при поклёвке",
    apply: ["fishing"],
    rarity: "Ultimate",
    maxLevel: 4,
  },
  {
    name: "Bait",
    nameRu: "Наживка",
    desc: "Chance to receive double fishing drops",
    descRu: "Шанс получить двойной улов",
    apply: ["fishing"],
    rarity: "Legendary",
    maxLevel: 3,
  },
  {
    name: "Fire Hook",
    nameRu: "Огненный крючок",
    desc: "The hook is on fire",
    descRu: "Крючок горит",
    apply: ["fishing"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Hook",
    nameRu: "Крючок",
    desc: "Get more exp from fishing",
    descRu: "Больше опыта с рыбалки",
    apply: ["fishing"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Hook Luck",
    nameRu: "Удача рыбака",
    desc: "Chance to increase luck while fishing",
    descRu: "Шанс увеличить удачу при рыбалке",
    apply: ["fishing"],
    rarity: "Ultimate",
    maxLevel: 3,
  },
  {
    name: "Poisoned Hook",
    nameRu: "Ядовитый крючок",
    desc: "Poisons the hook",
    descRu: "Крючок отравлен",
    apply: ["fishing"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Sharpness Hook",
    nameRu: "Острый крючок",
    desc: "Deal damage with the hook",
    descRu: "Крючок наносит урон",
    apply: ["fishing"],
    rarity: "Ultimate",
    maxLevel: 1,
  },
  {
    name: "Snap",
    nameRu: "Рывок",
    desc: "Pull hit entity towards you",
    descRu: "Притягивает пойманный объект к тебе",
    apply: ["fishing"],
    rarity: "Elite",
    maxLevel: 3,
  },

  // ─── ELYTRA ───────────────────────────────────────────────
  {
    name: "Judgement",
    nameRu: "Судный день",
    desc: "Chance of poisoning opponent and gaining regeneration",
    descRu: "Шанс отравить атакующего и получить регенерацию",
    apply: ["elytra"],
    rarity: "Legendary",
    maxLevel: 5,
  },
  {
    name: "Momentum",
    nameRu: "Импульс",
    desc: "Chance of speed boost when taking off with elytra",
    descRu: "Шанс ускорения при взлёте с фейерверком",
    apply: ["elytra"],
    rarity: "Elite",
    maxLevel: 3,
  },
  {
    name: "Reinforced",
    nameRu: "Усиленный",
    desc: "Reduces damage dealt to you",
    descRu: "Снижает входящий урон в полёте",
    apply: ["elytra"],
    rarity: "Ultimate",
    maxLevel: 4,
  },
  {
    name: "Rush",
    nameRu: "Рывок",
    desc: "Chance of speed boost when taking off. Costs 10 souls",
    descRu: "Шанс ускорения при взлёте. Стоит 10 душ",
    apply: ["elytra"],
    rarity: "Fabled",
    maxLevel: 3,
  },
  {
    name: "Slingshot",
    nameRu: "Рогатка",
    desc: "Boost yourself into flight by right-clicking",
    descRu: "Подбрасывает в воздух при ПКМ",
    apply: ["elytra"],
    rarity: "Legendary",
    maxLevel: 3,
  },
];
