export const UI_TEXT = {
  en: {
    title: "Advanced Enchantments",
    subtitle: "Complete reference",
    searchPlaceholder: "Search enchantment...",
    category: "CATEGORY",
    rarity: "RARITY",
    all: "All",
    showing: "Showing",
    of: "of",
    enchants: "enchants",
    level: "Lv.",
    notFound: "Nothing found",
    enchantments: "enchantments",
  },
  ru: {
    title: "Advanced Enchantments",
    subtitle: "Полный справочник",
    searchPlaceholder: "Поиск чары...",
    category: "КАТЕГОРИЯ",
    rarity: "РЕДКОСТЬ",
    all: "Все",
    showing: "Показано",
    of: "из",
    enchants: "чар",
    level: "Ур.",
    notFound: "Ничего не найдено",
    enchantments: "чарок",
  },
};
